{% set name = "mike" %}
{% set version = "2.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mike-{{ version }}.tar.gz
  sha256: abd79b8ea483fb0275b7972825d3082e5ae67a41820f8d8a0dc7a3f49944e810

build:
  number: 0
  noarch: python
  entry_points:
    - mike = mike.driver:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - jinja2 >=2.7
    - mkdocs >=1.0
    - pyparsing >=3.0
    - pyaml >=5.1
    - verspec
    - importlib-resources
    - importlib-metadata

test:
  imports:
    - mike
    - mike.templates
  commands:
    - pip check
    - mike --help
  requires:
    - pip

about:
  home: https://github.com/jimporter/mike
  summary: Manage multiple versions of your MkDocs-powered documentation
  license: BSD-3-Clause
  # License file manually packaged. See https://github.com/jimporter/mike/pull/23
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
