{% set name = "mike" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mike-{{ version }}.tar.gz
  sha256: 93e0a3a904311ebb432d3210242cca38286fb1ff1944e08bb1e7b46c149ebce1

build:
  number: 0
  noarch: python
  entry_points:
    - mike = mike.driver:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jinja2
    - mkdocs >=1.0
    - python >=3.6
    - pyaml
    - verspec

test:
  imports:
    - mike
    - mike.templates
  commands:
    - pip check
    - mike --help
  requires:
    - pip

about:
  home: https://github.com/jimporter/mike
  summary: Manage multiple versions of your MkDocs-powered documentation
  license: BSD-3-Clause
  # License file manually packaged. See https://github.com/jimporter/mike/pull/23
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
