context:
  name: mike
  version: 2.1.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mike-${{ version }}.tar.gz
  sha256: abd79b8ea483fb0275b7972825d3082e5ae67a41820f8d8a0dc7a3f49944e810

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - mike = mike.driver:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - jinja2 >=2.7
    - mkdocs >=1.0
    - pyparsing >=3.0
    - pyaml >=5.1
    - verspec
    - pyyaml_env_tag
    - importlib-resources
    - importlib-metadata

tests:
  - python:
      imports:
        - mike
        - mike.templates
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - mike --help

about:
  summary: Manage multiple versions of your MkDocs-powered documentation
  license: BSD-3-Clause
  # License file manually packaged. See https://github.com/jimporter/mike/pull/23
  license_file: LICENSE
  homepage: https://github.com/jimporter/mike

extra:
  recipe-maintainers:
    - hadim
